### PR TITLE
Remove duplicates created

### PR DESCRIPTION
**Pull request by cossorzano**

### CODE REVIEW

**Comment by dmaluenda** [comment]
It's not able to work in streaming, right? It would be nice if so..

**Comment by cossorzano** [comment]
It would certainly be. But I don't know how to make protocols in streaming

**Comment by dmaluenda** [comment]
I'm working in the streaming version in this branch and I think it will be ready soon. Thus, let me finish before merging this PR.

**Comment by dmaluenda** [comment]
I've refactorized the ConsensusPicking protocol in order to inherit from it and use it as base.

**Pull request merged**
