### PR TITLE
Added support for reading EER movies to FlexAlign

### PR DESCRIPTION
**Pull request by oierlauzi**
Requires https://github.com/I2PC/xmippCore/pull/197 to be merged first
Adds EER processing capabilities to FlexAlign. Other movie processing protocols remain pending

### CODE REVIEW

**Comment by albertmena** [comment]
image
Not sure if is something local or general. The dataset is from empiar/11487

**Comment by oierlauzi** [comment]
That is because of the gain function. Try running it without the gain. I dont know why its not being able to read that .gain file

**Comment by albertmena** [comment]
Removing the gain file from importMovie the error chages:
image
Any case we should to check the protocol with the gain file imported, maybe other dataset

**Comment by oierlauzi** [comment]
Did you switch branches in core?

**Comment by oierlauzi** [comment]
> Removing the gain file from importMovie the error chages: image Any case we should to check the protocol with the gain file imported, maybe other dataset

The warnings are expected

**Review by albertmena — APPROVED** [review]

**Review by albertmena — CHANGES_REQUESTED** [review]
With Gain file it fails:
image

I use an *.eer file and *.gain from: https://www.ebi.ac.uk/empiar/EMPIAR-11366/

**Review by albertmena — APPROVED** [review]
Congrats for the great work!

**Pull request merged**
