### PR TITLE
Removed unused XmippDataset class

### PR DESCRIPTION
**Pull request by delarosatrevin**
As part of the pyworkflow library cleanup, the unused class Dataset was removed...so we should remove this one as well from Xmipp plugin.

### CODE REVIEW

**Comment by dmaluenda** [comment]
Ok! Once [the Scipion's PR](https://github.com/I2PC/scipion/pull/1896) is merge, we can also merge this.

**Comment by pconesa** [comment]
I didn't know that.. @dmaluenda probably @delarosatrevin is better but you might need the manager changes from this one.

**Comment by dmaluenda** [comment]
As [the related Scipion's PR](https://github.com/I2PC/scipion/pull/1896) PR is merged, I will also merge this. Ok @delarosatrevin ?

**Comment by delarosatrevin** [comment]
Yes, I think so. Thanks @dmaluenda

**Pull request merged**
