### PR TITLE
Jmrt em refactor

### PR DESCRIPTION
**Pull request by delarosatrevin**
Should be reviewed together with https://github.com/I2PC/scipion/pull/1836

* Viewers from nma and proj_match submodules under xmipp3/protocols have been moved to xmipp3/viewers. 
* Removed visualization of base classes from XmippViewer, now in base class DataViewer

### CODE REVIEW

**Comment by azazellochg** [comment]
https://github.com/I2PC/scipion-em-xmipp/blob/jmrt-em-refactor/xmipp3/protocols/pdb/protocol_convert_pdb.py#L37 this import is incorrect.

**Comment by delarosatrevin** [comment]
Yes, it became incorrect on Friday, after the merge of the refactoring PR with the atomic modelling one...@fonsecareyna82 could update that?

**Comment by pconesa** [comment]
Can we delete the branch?

**Comment by rmarabini** [comment]
Yes, please

**Comment by delarosatrevin** [comment]
Already deleted! (according to GitHub, 21 hours ago now)

**Pull request merged**
