### PR TITLE
Expand doSaveMovie condition for tomo frame splitting, which requires…

### PR DESCRIPTION
**Pull request by JorMaister**
… movie save

### CODE REVIEW

**Review by DStrelak — APPROVED** [review]

**Review by cossorzano — APPROVED** [review]
OK

**Review by dmaluenda — APPROVED** [review]

**Comment by dmaluenda** [comment]
I agree on that, but it's a draft. Are you sure it's finished? If so, let's merge it.

**Comment by pconesa** [comment]
Hold this, I've got to find a cleaner way if exists.

**Comment by dmaluenda** [comment]
How is this going on?

**Comment by DStrelak** [comment]
> I've got something almost ready but flexalign is not outputting the movies. Maybe my installation has not the latest. ALmost there.

Let me know if you need help.

**Comment by pconesa** [comment]
There is a new implementation that does not require changes here

**Pull request closed without merging**
