### PR TITLE
Rs improve deep consensus

### PR DESCRIPTION
**Pull request by rsanchezgarc**
- tensorflow with cuda 10
- deep consensus custom coordinates

### CODE REVIEW

**Comment by rsanchezgarc** [comment]
More options for deep consensus. Installation part will be ignored when using conda envs

**Comment by dmaluenda** [comment]
Are you sure that you want to do this PR against devel instead of python3_migration or, even, rsg_conda_support?

**Comment by rsanchezgarc** [comment]
I don't mind, I just asked for it  to remind that this was ready. I leave the decision to you

**Comment by dmaluenda** [comment]
Since I don't know why Travis is not passing, I've just included this changes in https://github.com/I2PC/scipion-em-xmipp/pull/232.

Then, I close this.

**Comment by DStrelak** [comment]
> Since I don't know why Travis is not passing

The [build](https://travis-ci.com/github/I2PC/scipion-em-xmipp/builds/164759178) got stuck. It happens sometimes

**Comment by dmaluenda** [comment]
I relaunched a couple of times getting the same timeout error...

**Comment by DStrelak** [comment]
That also happens. I think that it's caused by corrupted image or sth. 
What you can try in that case is to request new build, either by empty commit or by Trigger build feature on Travis (click More options -> Trigger build)

**Pull request closed without merging**
