### PR TITLE
FlexAlign: fixing tests, removing unused protocol (Movie average)

### PR DESCRIPTION
**Pull request by DStrelak**

### CODE REVIEW

**Review by albertmena — DISMISSED** [review]

**Comment by albertmena** [comment]
Delete it https://github.com/I2PC/scipion-em-xmipp/blob/f1e7977b43c15340a51952cceca74625e301c9c8/xmipp3/protocols/protocol_flexalign.py#L412

**Comment by DStrelak** [comment]
> Delete it
> 
> https://github.com/I2PC/scipion-em-xmipp/blob/f1e7977b43c15340a51952cceca74625e301c9c8/xmipp3/protocols/protocol_flexalign.py#L412

No, that's on purpose, to show error message when somebody tries to apply crop. The problem is that the layout of the protocol is inherited and I can't (I don't know how to ) remove the fields for crop.

**Comment by albertmena** [comment]
> > Delete it
> > https://github.com/I2PC/scipion-em-xmipp/blob/f1e7977b43c15340a51952cceca74625e301c9c8/xmipp3/protocols/protocol_flexalign.py#L412
> 
> No, that's on purpose, to show error message when somebody tries to apply crop. The problem is that the layout of the protocol is inherited and I can't (I don't know how to ) remove the fields for crop.

You can get the params of the inherited protocol[ with getParam](https://scipion-em.github.io/docs/release-3.0.0/api/pyworkflow/pyworkflow.protocol.params.html#pyworkflow.protocol.params.Form.getParam), and remove it with form._paramsDict. (thanks @pconesa )

**Review by albertmena — CHANGES_REQUESTED** [review]
Doesn't run test  

- TestMaxShift.testFilterRejectBoth
- Correlationaligment due to the crop parameter
- TestMixedMovies.test_CorrelationOpticalFlow

**Review by albertmena — APPROVED** [review]

**Pull request merged**
