### PR TITLE
Ds fixing test

### PR DESCRIPTION
**Pull request by DStrelak**
https://sonarcloud.io/project/issues?id=Xmipp&issues=AWXOXsfRashydt7k-IiD&open=AWXOXsfRashydt7k-IiD

### CODE REVIEW

**Comment by dmaluenda** [comment]
Ouch! Again, this include the two before ^^. For me, the three are right excepting for the import in the 3Dresolution in the #7. Once fix, this PR can be merged and the other two can be close.

Nice bug fixing and cleaning code!!

**Comment by dmaluenda** [comment]
Just to remind, once the `createXmippInputVolumes` is removed from [here](https://github.com/I2PC/scipion-em-xmipp/blob/c059467f572164accc2bab98a19db9a83acc22d3/xmipp3/protocols/protocol_resolution3d.py#L35) we can merge this and close #7 and #8 . What do you think @DStrelak ?

**Comment by DStrelak** [comment]
Yes, @dmaluenda .
I'm actually considering canceling these pull requests and do them again, without overlap (that was a beginners mistake on my part).
I will do that during this week (fingers crossed) :)

**Comment by dmaluenda** [comment]
Ok, don't worry! It was just a remind ;)

**Pull request merged**
