### PR TITLE
Fix cudnn

### PR DESCRIPTION
**Pull request by rsanchezgarc**
Fix small bug installling cudnn due to new versions

### CODE REVIEW

**Comment by dmaluenda** [comment]
I changed some things there. We should merge them to skip the conflict.

**Comment by dmaluenda** [comment]
We should avoid prints and raise, because every time that `./scipion install*` is launched, the code passes to here independently if you wants to install xmipp, deepLearningToolkit or whatever

**Comment by rsanchezgarc** [comment]
Sure, if there are prints, bad for me, I forgot to remove them. They are not needed at all haha.
Do I have to do anything else?

**Comment by dmaluenda** [comment]
It's enough, I will test and merge it. Thx!

**Pull request merged**
