### PR TITLE
devel << release-20.07

### PR DESCRIPTION
**Pull request by dmaluenda**

### CODE REVIEW

**Comment by dmaluenda** [comment]
There is a conflict in monores viewer.

```
<<<<<<< release-20.07
        if self.protocol.halfVolumes.get() is True:
=======
        if self.protocol.hasAttribute('halfVolumes'):
>>>>>>> devel
```

Which one is the good one, @Vilax ?

**Comment by dmaluenda** [comment]
I'm not capable to resolve the conflict here.... I need help @Vilax @rmarabini (even @JorMaister ) maybe it was fixed in previous PR..

**Comment by rmarabini** [comment]
Hi @dmaluenda,

  In all cases branch devel is right and branch release-20.07 is wrong. The code for visualization is now centralized in "mapVolsWithColorkey" instead of repeated in each viewer.

**Comment by dmaluenda** [comment]
Thank you very much @rmarabini !!

**Comment by DStrelak** [comment]
@Vilax , can you have a look at the conflict (xmipp3/viewers/viewer_resolution_monogenic_signal.py)? Thanks.

**Comment by dmaluenda** [comment]
Afeter fixing the conflict, merge together with https://github.com/I2PC/xmipp/pull/297, https://github.com/I2PC/xmippViz/pull/40 and https://github.com/I2PC/xmippCore/pull/77

**Comment by pconesa** [comment]
I think we need an intermediate branch, there is no way to solve conflicts in release, unless we accept all release changes.

**Pull request closed without merging**
